feat: add an action to test contract on CI
Finschia/finschia-wasm pull request #15
Opened 2024-02-15 07:08 UTC by kokeshiM0chi

2024-02-15 08:34 UTC, 170210 requested changes

2024-02-15 08:34 UTC, 170210 commented on .github/workflows/tests-contracts.yaml
> +          docker pull finschia/finschianode:2.0.1
Please do not hard coding.

2024-02-15 08:34 UTC, 170210 commented on .github/workflows/tests-contracts.yaml
> +          sleep 5
Is this the same as https://github.com/Finschia/finschia-wasm/blob/main/scripts/start_integration_test_contracts.sh　

2024-02-19 02:11 UTC, kokeshiM0chi commented
https://github.com/Finschia/finschia-wasm/pull/16

Replace it with this PR.

2024-02-19 02:11 UTC, closed without merging